#!/usr/bin/env ruby
ENV["gubg"] = "#{ENV["HOME"]}/gubg" unless ENV.has_key?("gubg")
input_fn = "#{ENV["HOME"]}/nontech/auro.naft"
if ARGV.empty?
    system("time_track -i #{input_fn}")
else
    system("time_track -i #{input_fn} -f #{ARGV[0]}")
end
