#!/usr/bin/env ruby
require("open3")

input_fp = "#{ENV["HOME"]}/decode-it/auro/todo.md"

Open3.capture2e("dpn", "Update", "-i", input_fp)

args = ["dpn", "list", "-i", input_fp, "-V", "0"]
args << "-d" if ARGV.include?("d")
output, status = Open3.capture2e(*args)
puts output
